config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :links, :only => [:new, :create, :edit, :update, :destroy]

  namespace :admin do
    resources :links
    resources :users
  end

  root 'links#new'

  get 'list'  => 'links#list'
  get 'about' => 'static_pages#about'
  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'
  get 'admin/search'  => 'admin/search#search'
  get 'admin/search/results'  => 'admin/search#results'

  match '/:short' => 'links#show', :via => [:get]

end

app/models/link.rb
class Link < ActiveRecord::Base
	validates :url, :presence => true
	validates :url, :url => true
	before_create :randomize_short
	
	belongs_to :user

	private

	def randomize_short
		until !Link.where(short: short).exists?
  		self.short = SecureRandom.urlsafe_base64(4)
		end
	end
	
end

app/models/message.rb
class Message

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true,
    length: { maximum: 200 }

  validates :email,
    presence: true,
    length: { maximum: 200 }

  validates :content,
    presence: true,
    length: { maximum: 5000 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links, dependent: :destroy

end

app/controllers/admin/links_controller.rb
class Admin::LinksController < ApplicationController
	before_action :require_admin

  def index
    	@links = Link.all
  end

end

app/controllers/admin/search_controller.rb
class Admin::SearchController < ApplicationController
  before_action :require_admin

  def results
    if params[:type] == "email"
      search_email
    elsif params[:type] == "id"
      search_id
    elsif params[:type] == "short"
      search_short
    end  
  end

  def search_email
    if @users = User.find_by_email(params[:search]).nil?
      flash[:notice] = "Email Not Found"
      redirect_to admin_search_path
    else
      @users = User.find_by_email(params[:search])           
    end
  end

  def search_id
    if @users = User.find_by_id(params[:search]).nil?
      flash[:notice] = "ID Not Found"
      redirect_to admin_search_path
    else
      @users = User.find_by_id(params[:search])
    end
  end

  def search_short
    if @links = Link.find_by_short(params[:search]).nil?
      flash[:notice] = "Short URL Not Found"
      redirect_to admin_search_path
    else
      @links = Link.find_by_short(params[:search])
    end
  end  

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def index
    @users = User.all
  end

  def show
    @users = User.find(params[:id]).links
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
 
  def require_admin
    if !current_user.try(:admin?)
    	flash[:notice] = "Link Not Found"
      redirect_to root_path
    end	
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def new
    @shortened_url = Link.new
  end
 
  def create
    @shortened_url = Link.new(link_params)

    if user_signed_in?
      @shortened_url.user_id = current_user.id
    end

    if @shortened_url.save
      flash[:shortened_short] = @shortened_url.short
      redirect_to new_link_url
    else
      render :action => "new"
    end
  end
 
  def show
    @shortened_url = Link.find_by_short(params[:short])
    if @shortened_url
      @shortened_url.update_attribute(:count, @shortened_url.count + 1)
      redirect_to @shortened_url.url
    else
      flash[:notice] = "Link Not Found"
      redirect_to root_path
    end
  end

  def list
    if user_signed_in?
      @listall = current_user.links
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    Link.find(params[:id]).destroy
    flash[:notice] = "Link Removed"
    redirect_to :controller => 'links', :action => 'list'
  end

  def update
    @shortened_url = Link.find(params[:id])
    respond_to do |format|
      if @shortened_url.update(link_params)
        format.html { redirect_to(@shortened_url_url, :notice => 'Link was successfully updated.') }
        format.json { respond_with_bip(@shortened_url) }
      else
        format.json { respond_with_bip(@shortened_url) }
      end
    end
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    
    if @message.valid?
      MessageMailer.new_message(@message).deliver_now
      redirect_to contact_path, notice: "Your messages has been sent."
    else
      flash[:alert] = @message.errors.full_messages.to_sentence
      render :new
    end
  end

  private

    def message_params
      params.require(:message).permit(:name, :email, :content)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/admin/links_helper.rb
module Admin::LinksHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/links/index.html.erb
<div class="container">
  <h2>Here are all the shortened urls:</h2>

  <table id="links" class="table table-striped">
    <thead>
      <tr>
        <th>URL</th>
        <th>Short URL</th>
        <th>Clicks</th>
        <th>Registered</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      <% @links.each do |list| %>
        <tr>
          <td><%= best_in_place list, :url, :as => :input, :value => list.url, :ok_button => 'Save', :cancel_button => 'Cancel', :display_with => :truncate, :helper_options => {:length => 60} %></td>
          <td><%= link_to root_url.to_s + list.short.to_s, root_url.to_s + list.short.to_s %></td>
          <td><%= list.count %></td>
          <% if list.user_id? %>
            <td><%= link_to list.user.email, admin_user_path(list.user_id) %></td>
          <% else %>
            <td>No</td>
          <% end %>
          <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %></td>
        </tr>

      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/search/index.html.erb
<%= form_tag(admin_users_search_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/admin/search/results.html.erb
<% if @users %>

<div class="container">
  <h2>Here are all the users:</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th>Last Login</th>
        <th>Last IP</th>
        <th>Links</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @users.email %></td>
          <td><%= @users.last_sign_in_at %></td>
          <td><%= @users.last_sign_in_ip %></td>
          <td><%= link_to "View Links", admin_user_path(@users.id) %></td> 
    </tbody>
  </table>
</div>

<% end %>

<% if @links %>

<div class="container">
  <h2>Link:</h2>
 <table class="table table-striped">
    <thead>
      <tr>
        <th>URL</th>
        <th>Short URL</th>
        <th>Clicks</th>
        <th>Registered</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= best_in_place @links, :url, :as => :input, :value => @links.url, :ok_button => 'Save', :cancel_button => 'Cancel', :display_with => :truncate, :helper_options => {:length => 60} %></td>
          <td><%= link_to root_url + @links.short, root_url + @links.short %></td>
          <td><%= @links.count %></td>
          <% if @links.user_id? %>
            <td><%= link_to @links.user.email, admin_user_path(@links.user_id) %></td>
          <% else %>
            <td>No</td>
          <% end %>
          <td><%= link_to 'Delete', @links, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %></td>
        </tr>
    </tbody>
  </table>
</div>

<% end %>

app/views/admin/search/search.html.erb
<h2>Search</h2>
<%= form_tag(admin_search_results_path, :method => "get", id: "search-form") do %>
	<%= select_tag(:type, options_for_select([['Email', "email"], ['User ID', "id"], ['Short URL', "short"]], selected: params[:type] )) %>
  <%= text_field_tag :search, params[:search], placeholder: "Search for..." %>
  <%= submit_tag "Search", :name => nil, class: "btn btn-success"%>
<% end %>

app/views/admin/users/index.html.erb
<div class="container">
  <h2>Here are all the users:</h2>
  <table id="users" class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th>Last Login</th>
        <th>Last IP</th>
        <th>Links</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.last_sign_in_at %></td>
          <td><%= user.last_sign_in_ip %></td>
          <td><%= link_to "View Links", admin_user_path(user.id) %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/search.html.erb
<%= form_tag(users_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/admin/users/show.html.erb
<div class="container">
  <h2>Here are all the links:</h2>
  <table id="users" class="table table-striped">
    <thead>
      <tr>
        <th>URL</th>
        <th>Short URL</th>
        <th>Clicks</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |link| %>
        <tr>
          <td><%= best_in_place link, :url, :as => :input, :value => link.url, :ok_button => 'Save', :cancel_button => 'Cancel', :display_with => :truncate, :helper_options => {:length => 60} %></td>
          <td><%= link_to root_url + link.short, root_url + link.short %></td>
          <td><%= link.count %></td>
          <td><%= link_to 'Delete', link, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    FW.GG - URL Shortner
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "FW.GG", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if user_signed_in? %>
  						<li><%= link_to "My Links", list_path %></li>
              <li><%= link_to "My Account", edit_user_registration_path %></li>
  						<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
						<% else %>
  						<li><%= link_to('Sign In', new_user_session_path)  %></li>
  						<li><%= link_to('Sign Up', new_user_registration_path)  %></li>
						<% end %>
            <%if current_user.try(:admin?) %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Admin <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Search", admin_search_path %></li>
                  <li><%= link_to "User Admin", admin_users_path %></li>
                  <li><%= link_to "Link Admin", admin_links_path %></li>
                </ul>
              </li>    
            <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>URL Shortner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container center">

<% if flash[:shortened_short].present? %>
  <p class='alert alert-success'>
    The shortened url is available here: <%= link_to root_url + flash[:shortened_short], root_url + flash[:shortened_short] %>
  </p>
<% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

<%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/links/list.html.erb
<div class="container">
  <h2>Here are all your current shortened urls:</h2>
  <table id="links" class="table table-striped">
    <thead>
      <tr>
        <th>URL</th>
        <th>Short URL</th>
        <th>Clicks</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @listall.each do |list| %>
        <tr>
          <td><%= best_in_place list, :url, :as => :input, :value => list.url, :ok_button => 'Save', :cancel_button => 'Cancel', :display_with => :truncate, :helper_options => {:length => 60} %></td>
          <td><%= link_to root_url.to_s + list.short.to_s, root_url.to_s + list.short.to_s %></td>
          <td><%= list.count %></td>
          <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/links/new.html.erb
<%= form_for @shortened_url do |form| %>
<h1>URL Shortner</h1>
  <% if @shortened_url.errors[:url].any? %>
    <p class='alert alert-danger'>
      The given url <%= @shortened_url.errors[:url].to_sentence %>.
    </p>
  <% end %>
 
  <p>
    <%= form.label :url, "Your URL:" %>
    <%= form.text_field :url, :value => "http://", :size=>"60", :onclick => 'this.select();' %>
  </p>

	<%= form.submit "Shorten my URL", class: "btn btn-success btn-lg" %>

<% end %>

app/views/messages/new.html.erb
<h1>Contact</h1>

<%= form_for @message, url: contact_path do |message_form| %>
  <fieldset>
    <p>
      <div class="field">
        <%= message_form.label :name %><br />
        <%= message_form.text_field :name %>
      </div>
    </p>
    
    <p>
      <div class="field">
        <%= message_form.label :email %><br />
        <%= message_form.email_field :email %>
      </div>
    </p>

    <p>
      <div class="field">
        <%= message_form.label :message %><br />
        <%= message_form.text_area :content, :size => "50x10"%>
      </div>
    </p>
  </fieldset>
  
  <fieldset>
    <div class="field">
      <%= message_form.submit "Send", class: "btn btn-success" %>
    </div>
  </fieldset>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>

<p>
It's a URL shortner written in Rails.
</p>